FROM node:20-alpine
RUN mkdir -p /usr/app
WORKDIR /usr/app
COPY . /usr/app

RUN mkdir -p $HOME/docker/volumes/postgres

# --no-cache: download package index on-the-fly, no need to cleanup afterwards
# --virtual: bundle packages, remove whole bundle at once, when done
RUN apk --no-cache --virtual build-dependencies add \
    python3 \
    make \
    g++ \
    && npm install \
    && npm rebuild bcrypt --build-from-source \
    && apk del build-dependencies
