version: '2'
services:
  web:
    build: .
    command: npm run prod
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: James
      DB_NAME: reflection_db
      DB_PASSWORD: qweqwe
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: James
      POSTGRES_DB: reflection_db
      POSTGRES_PASSWORD: qweqwe
    volumes:
      - ./create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data