version: '2'
services:
  web:
    build: 
      dockerfile: Dockerfile.dev
    command: npm run prod
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: James
      DB_NAME: reflection_db
      DB_PASSWORD: qweqwe
      ACCOUNT_SECRET: test-account-secret
      APP_SECRET: test-app-secret
      EMAIL_CLIENT_ADDRESS: loggableapp@gmail.com
      EMAIL_CLIENT_ID: 729794276972-06rd2lkqlnvt2m26a5387v91omt0n6h2.apps.googleusercontent.com
      EMAIL_CLIENT_SECRET: ${EMAIL_CLIENT_SECRET}
      EMAIL_REFRESH_TOKEN: ${EMAIL_REFRESH_TOKEN}
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: James
      POSTGRES_DB: reflection_db
      POSTGRES_PASSWORD: qweqwe
    volumes:
      - ./create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data